### ISSUE TITLE
Does not interact with the Composter

### ISSUE THREAD

**Issue by Jomeaga** [cech12/BrickHopper#1]
Love this mod to save some iron! Unfortunately it doesn't seem to be able to insert or pull out of a Composter like a regular hopper can. Is this intentional?

**Comment by cech12** [comment]
This is not the intention. I will look into this. :) Which version are you using?

**Comment by Jomeaga** [comment]
Brick Hopper 1.0.0 for 1.16

**Comment by cech12** [comment]
Fixed and released in 1.1.0
Thanks for your bug report! :)
